name: "test"
parameters:
  - name: parameter1
    type: string
    default: develop
variables:
  var1: valueVAR1
stages:
    - stage: justAStep
      displayName: I am the fist step
      jobs:
        - job: Testjob
          strategy:
           matrix:
             windows: 
               var2 : 'windows'
             ubuntu:
               var2: 'ubuntu'

          pool:
            vmImage: $(var2)-latest
          steps:
          
          - script: echo the 1st variable is $(var1)
          - bash: echo the 2nd variable is $(var2)
          - script: echo the 1st parameter is ${{parameters.parameter1}}
          - script: echo print only if the value of var2 is windows
            condition: eq(variables.var2, 'windows')

          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
               Write-Host this is the 2nd variable $(var1)